### ISSUE TITLE
Мелкие замечания от 14 июля (приоритет: высокий)

### ISSUE THREAD

**Issue by cfospbru** [Friendly-Products/FM#19]
1) В журнале "Операция" сделать по умолчанию период отбора документов - текущий год (с 1 января по сегодня)

2) Графы "Флаг", "Платеж в валюте УУ", "Комиссия в валюте УУ", "ID "контрагента", "Проект", "Документ", "Ответственный" - убрать из журнала

3) В форме документа "Операция":

- убрать поле ID контрагента
- сделать поле "Валюта операции" нередактируемым
- платеж в валюте УУ и комиссию в валюте УУ сделать нередактируемыми
- добавить поле "Дата инвойса" (рядом с полем "Дата")
- поле "Дата" переименовать в "Дата платежа"
- добавить поле "Счёт-корреспондент" типа "Документ.Операция", это надо для отражения внутрифирменных расчётов (мы это обсуждали).

В отчёте о ДДС:

- В шапке отчёта убрать слово RollerAds ))))) а также убрать дату и время формирования отчёта - совершенно лишняя инфа
- строки отчета выводить не курсивом, а нормальным шрифтом
- добавить в шапке отчёта поле, которое выводит сумму выделенных ячеек (по этой задаче дам комментарий, если будут затруднения)
- первую графу отчёта назвать "Код"

**Comment by cfospbru** [comment]
В расшифровке ДДС тоже в шапке стоит слово RollerAds. Вычисти пожалуйста это слово во всей базе, чтобы нигде оно не появлялось.

В расшифровке ДДС также заметил забавный баг: в графе "Дата" во всех строчках стоит 1 число отчётного месяца, а не реальная дата операции - просьба это пофиксить.

Ну и я бы убрал графу "Документ" в расшифровке, а открытие документа-регистратора сделал по клику в любой графе расшифровки.

**Comment by cheshirshik** [comment]
Все пункты выполнены, кроме поля суммирования выделенных ячеек. Прошу проверить. Задачу перевел в тестирование.
