### ISSUE TITLE
Отчёт об остатках и оборотах по счетам (приоритет: средний)

### ISSUE THREAD

**Issue by cfospbru** [Friendly-Products/FM#20]
Необходимо сделать отчет "Остатки и обороты по счетам". Шаблон отчета находится на вкладке "Форма отчёта об остатках в 1С" этого гуглодока: https://docs.google.com/spreadsheets/d/1Mv8GpHiBaZC8xpZTpMhmLz77Osj0NiGpeYyNpStsAFc/edit#gid=1552717547

В отчёте отображаются остатки и обороты по всем счетам, по которым есть либо остатки, либо обороты, отличные от нуля (то есть если в системе счет есть, а никаких движений по нему никогда не было, его в отчете не выводим).

Остатки и обороты выводим строго в валюте счета!

Но в самой нижней строке отчёта отображаем суммарный остаток по всем счетам, пересчитанный в доллары по курсу каждой валюты к доллару на дату начала и конца периода.

**Comment by cheshirshik** [comment]
Отчет загружен в рабочую базу. Задачу перевожу в тестирование.
