### ISSUE TITLE
Отчёт о прибылях и убытках - P&L (приоритет: средний)

### ISSUE THREAD

**Issue by cfospbru** [Friendly-Products/FM#22]
Формат отчёта находится на листе ОПУ следующего гуглдока:

https://docs.google.com/spreadsheets/d/1Mv8GpHiBaZC8xpZTpMhmLz77Osj0NiGpeYyNpStsAFc/edit#gid=687719523

Суть P&L: он формируется аналогично ДДС из транзакций, созданных документами Операция. Главное отличие P&L от ДДС: если операция ставится в ДДС в месяце, указанном в поле "Дата платежа", но в P&L она ставится в месяце, указанном в поле "Дата инвойса". Если поле "Дата инвойса" не заполнено, операция в P&L не идет вообще. В остальном - всё аналогично: строка отчёта выбирается исходя из статьи ДДС операции, все суммы указываются в долларах. Несколько полей P&L являются расчетными: 

Маржинальный доход = Доходы - Прямые расходы
Маржинальная рентабельность = Маржинальный доход / Доходы
Чистая прибыль = Маржинальный доход - Накладные расходы

**Comment by cheshirshik** [comment]
По работам выполнено:

+ Проверить цифры в отчете ДДС и цифры в документе "Закрытие месяца".
+ Проверить результат формирования отчета ДДС.
+ Модернезировать ОПУ. Чтобы он получал данные из регламентного регистра.
* Заложить в отчет проверку на сдвиг последовательности по закрытию месяца. Данные можно брать из документа "Закритие месяца". Дата закрытия <= карйнему периоду. Если больше, то сообщить о ситуации пользователю. Т.е. данные будут не актуальны и требуется перезакрытие периода.
+ Проверить результат формирования отчета ОПУ.
+ Отменить изменение операции для ОПУ.
+ Добавить проверку двойных расчетов закрытия месяца.

+ Перенести изменение в рабочую базу.
+ Обновить отчеты ДДС и ОПУ, проверить корректность их работы.

**Comment by cheshirshik** [comment]
Для корректного формирования ОПУ необходимо перезалить реест операций полем "дата инвойса". После необходимо создать документы "Закрытие месяца" для расчета курсовых разниц. Задачу перевожу в тестирование.
