### ISSUE TITLE
Доработка импорта реестра в части внутрифирменных расчетов

### ISSUE THREAD

**Issue by cfospbru** [Friendly-Products/FM#26]
Автоматизировать заполнение поля "Счет-корреспондент" документа "Операция" при импорте реестра из гугл докс.

**Comment by cfospbru** [comment]
Алгоритм работы обработки должен быть следующим:

1) Берутся все документы "Операция", у которых указана статья "Внутрифирменные расчеты".
2) В хронологическом порядке идем по этим документам.
3) Смотрим, какой счет и какая сумма указаны в графах "Корр. счет" и "Оборот по КС"
4) Отбираем все документы Операция, в которых указан счет из поля "Корр. счет", сумма из поля "Оборот по КС" и у которых не заполнено поле "Операция-корреспондент" (то есть у которых пока нет пары).
5) Если есть документ с той же датой, которая стоит в исходном документе, берем в пару его, если нет - берем в пару документ с максимально близкой датой.
6) Заполняем поле "Операция-корреспондент" у исходного документа и найденной ему пары ссылками друг на друга.
7) Переходим к следующему документу, пока все не закончатся.

Если у какого-то документа не находится пара - сообщаем об ошибке, так как такого не должно быть.

**Comment by cheshirshik** [comment]
Механизм реализован в новой версии обработки загрузки реестра. Задачу перевожу в тестирование.
