### ISSUE TITLE
Поговорить с Вовой про сервер.

### ISSUE THREAD

**Issue by cfospbru** [Friendly-Products/FM#3]
Обсудить сервер.

**Comment by cheshirshik** [comment]
* Требования к серверу:
Нам нужен сервер 1с на линуксе.

  * Установить на сервер ОС Убунту 20.04.
  * На сервере мне необходим доступ по SSH.
  * На сервере надо будет поднять сервер 1С (инструкции у меня есть, могу помочь).
  * Поднять веб сервер APACHE (инструкции есть, могу помочь).
  * Поднять сервер POSTGRES (инструкции есть, могу помочь).
  * Опубликовать базы (инструкции есть, могу помочь).
  * Организовать бэкапинг данных базы средствами POSTGRES и бэкап линукса.
  
  Конфигурация у нас будет самописаная и не такая требовательная к железу. С запасом можно взять:

8 CPU, 32 Gb RAM, 160гб свободного места. 

Сама база на старте будет не большая. Порядка 200мб, но со временем разрастется. До нескольких гигабайт. Все зависит от того, что мы в ней будем хранить.  
1С очень любит оперативную память. Если есть возможность поставить больше оперативки, то лучше поставить. До 128гб.
